# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "hadoop.fullname" . }}-hive-nn
  labels:
    app: {{ template "hadoop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hive-nn
spec:
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
  - name: dfs2
    port: 50010
  - name: ipc
    port: 50020
  - name: webhdfs
    port: 50075
  - name: metastore
    port: 9083
  - name: hiveserver2
    port: 10000
  - name: hiveserver2webui
    port: 10002
  clusterIP: None
  selector:
    app: {{ template "hadoop.name" . }}
    release: {{ .Release.Name }}
    component: hive-nn
