apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "hadoop.fullname" . }}-hive-nn
  labels:
    app: {{ template "hadoop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hdfs-nn
spec:
  selector:
    matchLabels:
      app: {{ template "hadoop.name" . }}
      release: {{ .Release.Name }}
      component: hive-nn
  minAvailable: {{ .Values.hive.dataNode.pdbMinAvailable }}
